### ISSUE TITLE
Extension should not open new tab

### ISSUE THREAD

**Issue by Studio384** [optimise-group/click2dial-for-yealink#11]
Right now, to make a call, the extension opens a new tab whenever the call option is used. This tab however doesn't need to do anything. Preferably, the request is made without opening a tab at all.

Might be of interest: https://stackoverflow.com/questions/26238516/chrome-extension-webrequest-redirect-to-existing-tab-without-opening-new-tab

**Comment by Studio384** [comment]
Force of habit, my bad.

**Comment by timothyvanderaerden** [comment]
This is a bit harder then I initially thought. I wanted to use `fetch` and perform the request in the background. But that's not possible for a couple of reasons.

1. The host needs to be set in the manifest, which we can't do since we don't know it yet.
2. Cors is set to `same-origin` on Yealink devices, so we can't perform requests with an authorization header.

So the only way is to open and close the tab? Which seems a bit "bugy"? Maybe we can set an option to close the tab so that the user knows we close it after x seconds?

**Comment by timothyvanderaerden** [comment]
In 1d45b72 I added the behavior of closing the tab after 1s, additionally it doesn't focus the tab when it's created. I'm not sure if we can get anything better then that, so I'm going to close this issue. @Studio384 if you have a better solution you may reopen it.

**Comment by Studio384** [comment]
This is basically the behavior a browser has when you try to open a download link in a new tab, so this seems fine to me. Could the timeout perhaps be reduced?

**Comment by timothyvanderaerden** [comment]
What timeout are you thinking of? I'm not sure if this can give problems on slower systems when we set this too low. On my system the lowest was 20ms, anything below that wouldn't send out a request.
